services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 654321
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata-prod:
