name: CI

on:
  push:
    branches: [master, main, develop]
  pull_request:

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Run coverage
        run: npm run test:coverage

      - name: Build all apps
        run: npx nx run-many --target=build --all
